name: Publish Gem

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: discourse/publish-rubygems-action@v2-beta
        env:
          GITHUB_TOKEN: ${{secrets.BUNDLE_GITHUB__COM}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_BUMP_RELEASE}}
          GIT_EMAIL: marcelotoledo5000@gmail.com
          GIT_NAME: 'Marcelo Toledo - Automated Release'
          RELEASE_COMMAND: |
            gem install bundler
            bundle exec rake release
