name: Publish Gem

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1
        id: changed-version
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          paths: lib/miga/version.rb

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.BUNDLE_GITHUB__COM}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_BUMP_RELEASE}}
          RELEASE_COMMAND: |
            gem install bundler
            bundle exec rake release
