name: Publish Gem

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1
        id: changed-version
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          paths: lib/miga/version.rb

      - name: Tag and deploy
        # if: steps.changed-version.outputs.changed == 'true'
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.BUNDLE_GITHUB__COM }}"
          RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_BUMP_RELEASE }}"
          RELEASE_COMMAND: |
            gem install bundler
            bundle exec rake release

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.BUNDLE_GITHUB__COM}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_BUMP_RELEASE}}
          RELEASE_COMMAND: |
            git config --global user.email "marcelotoledo5000@gmail.com"
            git config --global user.name "Marcelo Toledo - Automated Release"
            bundle exec rake release
