name: Ruby

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run tests with RSpec
      env:
        RAILS_ENV: test
      run: bundle exec rspec

    - name: Run Rubocop
      env:
        RAILS_ENV: test
      run: bundle exec rubocop --config .rubocop.yml
